fix image tags, fix image push

diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -11,19 +11,21 @@ if [[ ! -f hooks/names ]]; then
 fi
 
 while read line  
-do  
-  printf "\nPushing %s...\n" "$line"
-	docker push "$line" || (printf "\nCannot push %s" "$line"; exit 1)
-	# If neww version with alpline:latest
-	if [[ "${SOURCE_BRANCH}" =~ ^[0-9.]+$ ]] && [[ "$line" =~ .*alpine_latest ]]; then
-		ALT_NAMES=(
-			"${REPO_NAME}:latest"
-			"${REPO_NAME}:${SOURCE_BRANCH}")
-		for ALT_NAME in "${ALT_NAMES[@]}"; do
-			docker tag "$line" "${ALT_NAME}" 	|| (printf "\nCannot tag %s as %s" "$line" "${ALT_NAME}"; exit 1)
-			printf "\nPushing %s as %s...\n" "$line" "${ALT_NAME}"
-    	docker push "${ALT_NAME}" 				|| (printf "\nCannot push %s" "${ALT_NAME}"; exit 1)
-		done
-	fi  
+do
+	if [ -n "$line" ]; then
+		printf "\nPushing %s...\n" "$line"
+		docker push "$line" || (printf "\nCannot push %s" "$line"; exit 1)
+		# If neww version with alpline:latest
+		if [[ "${SOURCE_BRANCH}" =~ ^[0-9.]+$ ]] && [[ "$line" =~ .*alpine_latest ]]; then
+			ALT_NAMES=(
+				"${REPO_NAME}:latest"
+				"${REPO_NAME}:${SOURCE_BRANCH}")
+			for ALT_NAME in "${ALT_NAMES[@]}"; do
+				docker tag "$line" "${ALT_NAME}" 	|| (printf "\nCannot tag %s as %s" "$line" "${ALT_NAME}"; exit 1)
+				printf "\nPushing %s as %s...\n" "$line" "${ALT_NAME}"
+	    	docker push "${ALT_NAME}" 				|| (printf "\nCannot push %s" "${ALT_NAME}"; exit 1)
+			done
+		fi
+	fi
 done < hooks/names
 rm hooks/names
