update tag names

diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -14,10 +14,16 @@ while read line
 do  
   printf "\nPushing %s...\n" "$line"
 	docker push "$line" || (printf "\nCannot push %s" "$line"; exit 1)
-	if [[ "$SOURCE_BRANCH" =~ ^[0-9.]+$ ]] && [[ "$line" =~ .*alpine_latest ]]; then
-		docker tag "$line" "${REPO_NAME}:latest" || (printf "\nCannot tag %s as %s" "$line" "${REPO_NAME}:latest"; exit 1)
-		printf "\nPushing %s as %s...\n" "$line" "${REPO_NAME}:latest"
-    docker push "${REPO_NAME}:latest" || (printf "\nCannot push %s" "${REPO_NAME}:latest"; exit 1)
+	# If neww version with alpline:latest
+	if [[ "${SOURCE_BRANCH}" =~ ^[0-9.]+$ ]] && [[ "$line" =~ .*alpine_latest ]]; then
+		ALT_NAMES=(
+			"${REPO_NAME}:latest"
+			"${REPO_NAME}:${SOURCE_BRANCH}")
+		for ALT_NAME in "${ALT_NAMES[@]}"; do
+			docker tag "$line" "${ALT_NAME}" 	|| (printf "\nCannot tag %s as %s" "$line" "${ALT_NAME}"; exit 1)
+			printf "\nPushing %s as %s...\n" "$line" "${ALT_NAME}"
+    	docker push "${ALT_NAME}" 				|| (printf "\nCannot push %s" "${ALT_NAME}"; exit 1)
+		done
 	fi  
 done < hooks/names
 rm hooks/names
